###########################################################
# Configuration file for the Sphinx documentation builder #
###########################################################

# This file does only contain a selection of the most common options. 
# For a full list see the documentation:
# http://www.sphinx-doc.org/en/master/config


#######################
# Project information #
#######################

# Branding
project = 'Omniport'
documentation = 'Omniport documentation'
oneliner = 'The one true portal for any and every educational institute.'
group = 'Information Management Group'
authors = [
    'Dhruv Bhanushali', 
    'Praduman Goyal',
]
copyright = group
author = ', '.join(authors)

# Colouring
purple = '#8f52ec'
blue = '#5f6fe0'
white = '#ffffff'

# Versioning
version = ''
release = 'Rolling release'


#########################
# General configuration #
#########################

# Any Sphinx extension module names
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
]

# Any paths that contain templates
templates_path = [
    '_templates',
]

# The suffix of source filenames
source_suffix = '.rst'

# The master toctree document
master_doc = 'index'

# The language for content autogenerated by Sphinx
language = 'en'

# Files and directories to ignore when looking for source files
exclude_patterns = []

# The name of the Pygments style to use
pygments_style = None


########
# HTML #
########

# The theme to use for HTML and HTML Help pages
html_theme = 'alabaster'
html_theme_options = {
    # Sidebar
    'fixed_sidebar': True,
    'logo': 'site/op_logo.png',
    'description': ' ',  # Adds a bit of space below the logo
    
    # GitHub
    'github_user': 'IMGIITRoorkee',
    'github_repo': 'omniport-docker',
    'github_banner': 'github_banner.svg',
    'github_button': False,

    # Header and footer
    'show_relbars': True,
    'show_powered_by': False,

    # Colouring
    'anchor': blue,
    'anchor_hover_bg': white,
    'anchor_hover_fg': purple,

    'relbar_border': purple,

    'link_hover': blue,

    # Fonts
    'font_family': '"Open Sans", sans-serif',
    'font_size': '14px',

    'code_font_size': '1em',
    'code_font_family': '"Fira Code", monospace',
}

# Path to the favicon of the site
html_favicon = '_static/site/favicon.ico'

# Add any paths that contain custom static files
html_static_path = [
    '_static', 
    '_static/css',
]


#############
# HTML Help #
#############

# Output file base name for HTML help builder.
htmlhelp_basename = documentation


########
# EPUB #
########

# Bibliographic Dublin Core info
epub_title = project

# The unique identifier of the text
epub_identifier = 'https://omniport.readthedocs.io/'

# Files that should not be packed into the EPUP file
epub_exclude_files = [
    'search.html',
]


#########
# LaTeX #
#########

# The engine to use to compile .tex files
latex_engine = 'xelatex'

# LaTeX snippets overriding those Sphinx usually puts into the files
latex_elements = {
    # Sizes
    'papersize': 'a4paper',
    'pointsize': '10pt',

    # Preamble
    'preamble': (
        r'''
            \usepackage{fontspec}
            \usepackage{listings}
            \usepackage{lstfiracode}
            \usepackage[default]{lato}

            \setmonofont{Fira Code}[
                Contextuals=Alternate
            ]
            \lstset{
                style=FiraCodeStyle,
                basicstyle=\ttfamily
            }
            \ActivateVerbatimLigatures
        '''
    ),
}

# Path to the logo of the project
latex_logo = '_static/site/op_wordmark.png'

# Latex files
# (source start file, target name, title, author, documentclass)
latex_documents = [
    (
        master_doc, 
        'Omniport.tex', 
        documentation,
        author, 
        'manual'
    ),
]


################
# Manual pages #
################

# Manual pages
# (source start file, name, description, authors, manual section)
man_pages = [
    (
        master_doc, 
        project, 
        documentation,
        authors, 
        1,
    ),
]


##################
# Texinfo output #
##################

# Texinfo files
# (source start file, target name, title, author, dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc, 
        project, 
        documentation,
        author, 
        project, 
        oneliner,
        'Miscellaneous',
    ),
]


##############
# Extensions #
##############

# Intersphinx
intersphinx_mapping = {'https://docs.python.org/': None}

# To-do
todo_include_todos = True
