name: Documentation

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip

    - run: pip install --upgrade pip setuptools

    - run: pip install -r requirements.txt

    - run: make html SPHINXOPTS="-W --keep-going -n"
      working-directory: docs
